- hosts: builder
  sudo: yes
  connection: ssh

  pre_tasks:
    - lineinfile: line='127.0.0.1 docker-registry.example.com' dest=/etc/hosts

  roles:
    - role: docker_environment
      docker_opts: '--storage-driver=aufs'
    - role: known_hosts_github
    - role: ansible
    - role: docker_registry
    - role: java
    - role: jenkins
      tags: ['jenkins']
    - role: jenkins_deploy_keys
      tags: ['jenkins']
    - role: jenkins_jobs
      tags: ['jenkins_jobs']
